# Generated by Django 3.1.4 on 2021-05-28 13:47

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210523_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.SlugField(default=member.models.getRandomString, max_length=200, unique=True),
        ),
    ]
