# Generated by Django 3.1.4 on 2021-05-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210528_2205'),
        ('member', '0003_auto_20210528_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clubprofile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.clubprofile'),
        ),
    ]
