# Generated by Django 3.1.5 on 2021-05-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210514_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='code_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
