# Generated by Django 3.1.5 on 2021-05-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_content_code_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolecture',
            old_name='url',
            new_name='embeded_code',
        ),
    ]
