# Generated by Django 3.1.5 on 2021-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_otherlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherlink',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
