# Generated by Django 3.1.4 on 2021-05-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_auto_20210516_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Dob', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shortBio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='videolecture',
            old_name='embeded_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code',
        ),
        migrations.RemoveField(
            model_name='content',
            name='code_heading',
        ),
        migrations.RemoveField(
            model_name='upcominghackathon',
            name='date',
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='domain',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Android Development', 'Android Development'), ('IOT', 'IOT '), ('Machine Learning', 'Machine Learning'), ('AR/VR', 'AR/VR')], max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='media/Dashboard/ContentImages/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='paragraph2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.subtopic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.course'),
        ),
        migrations.DeleteModel(
            name='OtherLink',
        ),
    ]
