# Generated by Django 3.1.4 on 2021-05-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolecture',
            old_name='url',
            new_name='embeded_link',
        ),
    ]
