# Generated by Django 3.1.4 on 2021-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210528_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='code_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/Dashboard/ContentImages/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
    ]
