# Generated by Django 3.1.4 on 2021-05-28 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210528_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominghackathon',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subtopic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course'),
        ),
    ]
