# Generated by Django 3.1.4 on 2021-05-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210528_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='highlights',
            field=models.TextField(),
        ),
    ]
