# Generated by Django 3.1.4 on 2021-05-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210529_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubprofile',
            name='domain',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Android Development', 'Android Development'), ('IOT', 'IOT'), ('Machine Learning', 'Machine Learning'), ('AR/VR', 'AR/VR')], max_length=200),
        ),
    ]
